import { reactive } from 'vue'
/**
 * 定义state类型约束
 */
export type State = {
	hasLogin: boolean
	theme: string
}

/**
 * 定义state
 */
export const state = reactive({
	hasLogin: false,
	theme: 'default'
} as State)

/**
 * 定义actions
 */
export const setHasLogin = (key: boolean) => {
	state.hasLogin = key
	uni.setStorageSync('hasLogin', key)
}

export const setTheme = (key: string) => {
	state.theme = key
	uni.setStorageSync('theme', key)
}