import { UxRequestOptions, UxResponseFail } from "./types";

/**
 * 拦截器
 */
class UxInterceptor {
	/**
	 * 请求之前拦截
	 */
	beforeRequest(config : UxRequestOptions) : UxRequestOptions {
		return config
	}

	/**
	 * 响应之后拦截请求成功
	 */
	afterResponseSucc(response : UTSJSONObject) : UTSJSONObject {
		return response
	}

	/**
	 * 响应之后拦截请求失败
	 */
	afterResponseFail(error : UxResponseFail) : UxResponseFail {
		return error
	}
}

export default UxInterceptor